import { NextResponse } from "next/server";

interface TicketInput {
  subject: string;
  priority?: string;
}

/* ── Realistic mock emails keyed by rough cluster theme ── */
function buildMockEmail(
  clusterName: string,
  prevCount: number,
  currCount: number,
  pctChange: number
): string {
  return `Subject: [URGENT QA ALERT] ${pctChange}% Spike Detected — ${clusterName}

Dear Hardware Manufacturing & QA Team,

I am writing to escalate an urgent quality signal that demands immediate attention from your team.

Over the past 30-day window, our AI-powered support intelligence platform has detected a ${pctChange}% increase in customer-reported tickets related to "${clusterName}" (${prevCount} tickets → ${currCount} tickets). This rate of increase exceeds our critical threshold and strongly suggests a systemic issue originating from the manufacturing or firmware pipeline rather than isolated customer error.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SIGNAL SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Category: ${clusterName}
• Previous 30-day volume: ${prevCount} tickets
• Current 30-day volume: ${currCount} tickets
• Change: +${pctChange}% (CRITICAL THRESHOLD EXCEEDED)
• Detection method: Semantic clustering + trend analysis

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
REQUESTED ACTIONS (P0 — Within 24 hours)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. Audit the firmware version and hardware BOM of units shipped in the last 60 days
2. Cross-reference with the production change log for any component substitutions or supplier changes
3. Pull a statistically significant sample from the current batch for accelerated stress testing
4. Confirm whether this spike correlates with a specific regional distribution centre or SKU variant
5. Halt further shipments of flagged SKUs pending QA sign-off if root cause is confirmed

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CUSTOMER IMPACT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
At the current trajectory, we project ${Math.round(currCount * 1.3)} tickets in the next 30-day window if left unaddressed. Each unresolved ticket represents an average of 2.4 customer touchpoints and a significant risk to NPS and public reviews.

Please treat this as a P0 escalation. I will schedule a joint support–QA sync call for tomorrow at 10:00 AM to review findings. In the meantime, please reply with an initial assessment within 4 hours so we can update our support team with any known workarounds.

Best regards,
Kreo Support Intelligence Platform
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This alert was auto-generated by the Kreo Issue Intelligence System.
Do not reply to this automated message — use the Slack #support-escalations channel.`;
}

export async function POST(request: Request) {
  const body = await request.json().catch(() => ({}));
  const { clusterName, prevCount, currCount, tickets } = body as {
    clusterName: string;
    prevCount: number;
    currCount: number;
    tickets: TicketInput[];
  };

  const pctChange =
    prevCount > 0 ? Math.round(((currCount - prevCount) / prevCount) * 100) : 100;

  const apiKey = process.env.OPENAI_API_KEY;

  if (!apiKey) {
    return NextResponse.json({
      email: buildMockEmail(clusterName ?? "Issue Spike", prevCount ?? 0, currCount ?? 0, pctChange),
      mock: true,
    });
  }

  try {
    const { default: OpenAI } = await import("openai");
    const client = new OpenAI({ apiKey });

    const ticketSamples = (tickets ?? [])
      .slice(0, 6)
      .map((t) => `• [${t.priority ?? "Medium"}] ${t.subject}`)
      .join("\n");

    const completion = await client.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content:
            "You are the Head of Support at Kreo, a D2C hardware company. Write urgent, professional QA Alert emails to the hardware manufacturing team when AI detects support ticket spikes. Format: Subject line, opening paragraph with context, a 'SIGNAL SUMMARY' section with bullet stats, a 'REQUESTED ACTIONS (P0)' numbered list, a 'CUSTOMER IMPACT' paragraph, and a professional sign-off from 'Kreo Support Intelligence Platform'. Use plain text, not markdown.",
        },
        {
          role: "user",
          content: `Draft a QA Alert email for this spike:\n\nIssue Category: "${clusterName}"\nPrevious 30-day window: ${prevCount} tickets\nCurrent 30-day window: ${currCount} tickets\nChange: +${pctChange}%\n\nSample affected tickets:\n${ticketSamples}\n\nThe email must be addressed to the Hardware Manufacturing & QA Team and request immediate investigation with specific, actionable steps.`,
        },
      ],
      max_tokens: 600,
      temperature: 0.35,
    });

    const email =
      completion.choices[0]?.message?.content?.trim() ||
      buildMockEmail(clusterName ?? "", prevCount ?? 0, currCount ?? 0, pctChange);

    return NextResponse.json({ email, mock: false });
  } catch (err) {
    console.error("[/api/draft-qa-alert]", err);
    return NextResponse.json({
      email: buildMockEmail(clusterName ?? "", prevCount ?? 0, currCount ?? 0, pctChange),
      mock: true,
    });
  }
}
